# Generated by Django 4.1.5 on 2023-01-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('wishes', '0002_alter_wish_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='Products.product'),
        ),
    ]
