# Generated by Django 4.1.5 on 2023-01-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('su', 'submitted'), ('pr', 'proccesing'), ('de', 'deleiverd')], max_length=2, null=True),
        ),
    ]
