# Generated by Django 4.1.5 on 2023-01-13 12:21

import Products.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='product title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='product description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='product price')),
                ('discount', Products.models.IntegerRangeField(default=0, verbose_name='discount on this product')),
                ('active', models.BooleanField(default=True, verbose_name='is this product available')),
                ('cover', models.ImageField(blank=True, upload_to='product_covers/', verbose_name='Product cover')),
                ('slug', models.SlugField(null=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date time')),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment text')),
                ('rating', models.CharField(choices=[('1', 'Very bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], default='3', max_length=1, verbose_name='your score')),
                ('active', models.BooleanField(default=True, verbose_name='is this comment active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Products.product')),
            ],
        ),
    ]
